server:
  port: 5001

spring:
  application:
    name: taofun-monitor
  profiles:
    active: dev
  #配置中心
  cloud:
    config:
      fail-fast: true
      name: ${spring.application.name}
      profile: ${spring.profiles.active}
      discovery:
        enabled: true
        service-id: ruoyi-config

# 注册中心配置
eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://test:123456@localhost:3000/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
