server:
  port: 3000
eureka:
  instance:
    #hostname: eureka-center
    appname: 注册中心
    hostname: localhost
  client:
    registerWithEureka: false # 单点的时候设置为 false 禁止注册自身
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://test:123456@${eureka.instance.hostname}:${server.port}/eureka
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 4000
